title: 'Software Developer'
default_lang: en
author:
  name: 'Brandon Himes'
  email: admin@brandonhimes.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This is the portfolio site for Software Developer Brandon Himes'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
